language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

env:
    global:
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
        - SYMFONY_PHPUNIT_REMOVE="symfony/yaml" # keep Prophecy

php:
    - 7.2
    - 7.3
    - 7.4
    - nightly

matrix:
    include:
        - php: 7.2
          env:
              - SYMFONY_VERSION='3.4.*'
              - COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
              - SYMFONY_DEPRECATIONS_HELPER=weak
        - php: 7.3
          env:
              - SYMFONY_DEPRECATIONS_HELPER='max[self]=0'
              - SYMFONY_VERSION='4.3.*'
        - php: 7.4
          env:
              - SYMFONY_VERSION=5.0.*
              - COMPOSER_FLAGS="--prefer-stable"
              - DEPENDENCIES='beta'
        - php: 7.4
          env: DEPENDENCIES='dev'
        - php: nightly
          env: DEPENDENCIES='dev'

before_install:
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [[ $TRAVIS_PHP_VERSION == 'nightly' ]]; then composer config platform.php 7.4.99; composer config minimum-stability dev; composer remove knplabs/knp-menu; composer remove symfony/phpunit-bridge; composer require knplabs/knp-menu:^3.2; composer require phpunit/php-code-coverage:^9.0; composer require phpunit/phpunit:^9.3; fi;
    - if [ "$DEPENDENCIES" == "beta" ]; then perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json; fi;
    - |
        if [ "$SYMFONY_VERSION" != "" ]; then
            sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'$SYMFONY_VERSION'"/' composer.json;
        fi;

install:
    - composer update $COMPOSER_FLAGS
    - if [[ $TRAVIS_PHP_VERSION != 'nightly' ]]; then ./vendor/bin/simple-phpunit install; fi;
    - if [[ $TRAVIS_PHP_VERSION == 'nightly' ]]; then ./vendor/bin/phpunit; fi;

script:
    - composer validate --strict --no-check-lock
    - if [[ $TRAVIS_PHP_VERSION != 'nightly' ]]; then php ./vendor/bin/simple-phpunit; fi;
    - if [[ $TRAVIS_PHP_VERSION == 'nightly' ]]; then ./vendor/bin/phpunit; fi;
