language: php

sudo: false

cache:
    directory:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

env:
    global:
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
        - SYMFONY_PHPUNIT_REMOVE="symfony/yaml" # keep Prophecy

php:
    - 7.2
    - 7.3
    - 7.4snapshot

matrix:
    include:
        - php: 7.1
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' SYMFONY_DEPRECATIONS_HELPER=weak
        - php: 7.3
          env: DEPENDENCIES='dev'
          env: SYMFONY_DEPRECATIONS_HELPER='max[self]=0'
        # Test LTS version
        - php: 7.3
          env: SYMFONY_VERSION='^3'
    allow_failures:
        - php: 7.4snapshot

before_install:
    - if [ "$DEPENDENCIES" == "dev" ]; then composer config minimum-stability dev; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/lts:${SYMFONY_VERSION} --no-update; fi;

install:
    - composer update $COMPOSER_FLAGS --prefer-dist
    - ./vendor/bin/simple-phpunit install

script:
    - composer validate --strict --no-check-lock
    - ./vendor/bin/simple-phpunit -v
