language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

env:
    global:
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
        - SYMFONY_PHPUNIT_REMOVE="symfony/yaml" # keep Prophecy

php:
    - 7.2
    - 7.3
    - 7.4

matrix:
    include:
        - php: 7.2
          env:
              - SYMFONY_VERSION='3.4.*'
              - COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
              - SYMFONY_DEPRECATIONS_HELPER=weak
        - php: 7.3
          env:
              - SYMFONY_DEPRECATIONS_HELPER='max[self]=0'
              - SYMFONY_VERSION='4.3.*'
        - php: 7.4
          env:
              - SYMFONY_VERSION=5.0.*
              - COMPOSER_FLAGS="--prefer-stable"
        - php: 7.4
          env: DEPENDENCIES='dev'

before_install:
    - if [ "$DEPENDENCIES" == "dev" ]; then composer config minimum-stability dev; fi;
    - if [ "$DEPENDENCIES" == "beta" ]; then perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json; fi;
    - |
        if [ "$SYMFONY_VERSION" != "" ]; then
            sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'$SYMFONY_VERSION'"/' composer.json;
        fi;

install:
    - composer update $COMPOSER_FLAGS --prefer-dist
    - ./vendor/bin/simple-phpunit install

script:
    - composer validate --strict --no-check-lock
    - ./vendor/bin/simple-phpunit -v
